### ISSUE TITLE
Implement Intake

### ISSUE THREAD

**Issue by henrikvtcodes** [greenmountainrobotics/2024-Robot#10]
Implement Intake Subsystem
**Hardware Specs**
- 1x Drive Motor - Redline/775, controlled by Talon SRX/Victor SPX
- 2x Motor for linear deployment (climber in a box) - REV Brushless
- _maybe_ 1x motor for controlling height of intake apparatus

**Tasks Required**
- [ ] Create `Intake` Subsystem
	- _If Applicable_ create feedback/feedforward controller to hold intake apparatus position
- [ ] Write `IntakeIO`, including `IntakeIOInputs`
- [ ] Implement IO for Simulation & Real 2024 Robot
All files should be in a dedicated `intake` folder (sub-package)

**Comment by henrikvtcodes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Intake](https://trello.com/c/GiA4v89A/16-implement-intake)
