### ISSUE TITLE
Battery Detection

### ISSUE THREAD

**Issue by henrikvtcodes** [greenmountainrobotics/2024-Robot#4]
Implement a system to track batteries in robot code based on the system that 6328 uses. 
**Tasks**
- [x] Find & Purchase Barcode scanning hardware
- [x] Implement Barcode Scanning & Logging in software
- [ ] Implement battery reuse detection/prevention in software
- [x] Label all batteries with barcodes and human readable names

> [!NOTE]
> **This is a LOW PRIORITY task.**
