### ISSUE TITLE
Implement Climber

### ISSUE THREAD

**Issue by henrikvtcodes** [greenmountainrobotics/2024-Robot#6]
**Hardware Specs**
- [ ] 2x motors (CIM/TalonSRX)

**Tasks Required**
- [ ] Create `Climber` Subsystem
	- Create feedback controller to hold the climber position
- [ ] Write `ClimberIO`, including `ClimberIOInputs`
- [ ] Implement IO for Simulation & Real 2024 Robot
All files should be in a dedicated `climber` folder (sub-package)

Issue will be updated when hardware specs are known.

**To complete**
Create a separate branch, implement these changes, and create a pull request.

**Comment by henrikvtcodes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement climber](https://trello.com/c/CNh656tg/14-implement-climber)

**Comment by henrikvtcodes** [comment]
Motor type updated! Usin CIMs driven by TalonSRXs
