### ISSUE TITLE
Implement Shooter

### ISSUE THREAD

**Issue by henrikvtcodes** [greenmountainrobotics/2024-Robot#7]
**Hardware**
- [ ] 2x NEO + Spark Max pairs for shooter wheels
- [ ] 2x (unknown motors) for pivoting shooter apparatus

**Tasks Required**
- [ ] Create `Shooter` Subsystem
	- Create feedback/feedforward controllers for shooter pivot and flywheel
- [ ] Write `ShooterIO`, including `ShooterIOInputs`
- [ ] Implement IO for Simulation & Real 2024 Robot. 
  
All files should be in a dedicated `shooter` folder (sub-package)

**Comment by henrikvtcodes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Shooter](https://trello.com/c/3UOtKjDN/15-implement-shooter)
